# https://docs.gitlab.com/ee/ci/yaml/includes.html#single-string-or-array-of-multiple-values
# Reusing the pipeline

include:
  remote: 'https://gitlab.com/marcellodesales/dockerized-cicd-pipeline/raw/master/.gitlab-cicd-dockerized-pipeline.yaml'
