version: "3.6"

services:

  parking-plus-service:
    # https://github.com/intuit/unmazedboot/releases/tag/v0.5.0
    image: supercash/parking-plus-service
    build:
      context: .
      args:
        # https://hub.docker.com/r/intuit/unmazedboot-builder-gradle/tags/
        - UNMAZEDBOOT_BUILDER_GRADLE_VERSION=6.7.0-jdk8-hotspot-0.5.0
        # https://hub.docker.com/r/intuit/unmazedboot-linker/tags/
        - UNMAZEDBOOT_LINKER_VERSION=jdk11-alpine-0.5.0
        # https://hub.docker.com/r/intuit/unmazedboot-runner/tags/
        - UNMAZEDBOOT_RUNNER_VERSION=custom-jdk-alpine3.8-0.5.0
        # Variables from https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
        - UNMAZEDBOOT_BUILDER_GIT_SHA=${CI_COMMIT_SHORT_SHA:-000000}
        - UNMAZEDBOOT_BUILDER_GIT_BRANCH=${CI_COMMIT_BRANCH:-unknown}
    environment:
      - DEBUG_ENV=true
      # Rotate the token at https://developers.google.com/maps/gmp-get-started after errors
      # {"description":"You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable 
      # Learn more at https://developers.google.com/maps/gmp-get-started","error":500}%
      - GOOGLE_GCP_DISTANCEMATRIX_CREDENTIALS_APIKEY=AIzaSyAaG2Mvdkp8dSgNXZ_uFjigx_6iVPOjo_4
      #- JAVA_OPTS=--marcello
    ports:
      - 8082:8080
    # volumes:
    #    - "./samples/gradle-java-jdk8-x-jre11-custom/hooks/sources:/runtime/sources/"
    #    - "./samples/gradle-java-jdk8-x-jre11-custom/hooks/java-opts:/runtime/java-opts"
