### 
### Must run with "DOCKER_BUILDKIT=0 docker-compose build"
###

version: "3.8"

networks:
  supercash-data-network:
    external:
      name: supercash-data-network

services:

  # The service for parking lots
  parking-lot-service:    
    image: supercash/parking-lot-service
    build:
      context: .
      args:
        # https://hub.docker.com/r/intuit/unmazedboot-builder-gradle/tags/
        - UNMAZEDBOOT_BUILDER_GRADLE_VERSION=6.7.1-jdk15-hotspot-0.5.1
        # https://hub.docker.com/r/intuit/unmazedboot-linker/tags/
        - UNMAZEDBOOT_LINKER_VERSION=jdk15-alpine-0.5.0
        # https://hub.docker.com/r/intuit/unmazedboot-runner/tags/
        - UNMAZEDBOOT_RUNNER_VERSION=custom-jdk-alpine3.8-0.5.0
        # Variables from https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
        - UNMAZEDBOOT_BUILDER_GIT_SHA=${CI_COMMIT_SHORT_SHA:-UNMAZEDBOOT_BUILDER_GIT_SHA}
        - UNMAZEDBOOT_BUILDER_GIT_BRANCH=${CI_COMMIT_REF_NAME:-UNMAZEDBOOT_BUILDER_GIT_BRANCH}
        - UNMAZEDBOOT_BUILDER_GIT_PIPELINE_URL=${CI_PIPELINE_URL:-UNMAZEDBOOT_BUILDER_GIT_PIPELINE_URL}
    environment:
      - DEBUG_ENV=true
    ports:
      - 8082:8082
    networks:
      - supercash-data-network
