### 
### Must run with "DOCKER_BUILDKIT=0 docker-compose build"
###

version: "3.6"

services:

  # The service for parking lots
  parking-lot-service:    
    image: supercash/parking-lot-service
    
    build:
      context: .
      args:
        # https://hub.docker.com/r/intuit/unmazedboot-builder-gradle/tags/
        - UNMAZEDBOOT_BUILDER_GRADLE_VERSION=6.7.1-jdk15-hotspot-0.5.0
        # https://hub.docker.com/r/intuit/unmazedboot-linker/tags/
        - UNMAZEDBOOT_LINKER_VERSION=jdk15-alpine-0.5.0
        # https://hub.docker.com/r/intuit/unmazedboot-runner/tags/
        - UNMAZEDBOOT_RUNNER_VERSION=custom-jdk-alpine3.8-0.5.0
        # Variables from https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
        - UNMAZEDBOOT_BUILDER_GIT_SHA=${CI_COMMIT_SHORT_SHA:-000000}
        - UNMAZEDBOOT_BUILDER_GIT_BRANCH=${CI_COMMIT_BRANCH:-unknown}
    environment:
      - DEBUG_ENV=true
    ports:
      - 8082:8080
    # volumes:
    #    - "./samples/gradle-java-jdk8-x-jre11-custom/hooks/sources:/runtime/sources/"
    #    - "./samples/gradle-java-jdk8-x-jre11-custom/hooks/java-opts:/runtime/java-opts"
