version: "3.6"

services:

  parking-plus-service-tests:
    # https://github.com/intuit/unmazedboot/releases/tag/v0.5.0
    image: supercash/parking-plus-service-tests
    build:
      context: .
      dockerfile: tests.Dockerfile
    volumes:
      - ./build/docker-container-build-artifacts:/builder/build/
