feign:
  client:
    config:
      default:
        loggerLevel: FULL

cash:
  super:
    platform:
      service:
        pagarme:
          url: http://pagarme-service:8120/v1
        parkinglot:
          url: https://maceio.parkingplus.com.br/servicos
          userKey: f313d6a3e46e2a1e1554ed7eb7d286310b924f8f
          retryableDestinationHosts:
            - maceio.parkingplus.com.br
            - demonstracao.parkingplus.com.br
            - localhost