# https://docs.spring.io/spring-boot/docs/1.1.0.M1/reference/html/howto-database-initialization.html#howto-initialize-a-database-using-hibernate
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop