spring:

  #configs to connect to self register the admin server as a client
  boot:
    admin:
      client:
        instance:
          # The Gateway will forward the calls to /auth/actuator/info...
          management-base-url: https://api-dev.super.cash
          metadata:
            tags:
              env: dev
              cluster: pdc
              segment: ppd

  datasource:
    url: jdbc:postgresql://supercash-ppd-dev.csdmsoazeise.sa-east-1.rds.amazonaws.com:5432/supercash?createDatabaseIfNotExist=true
    username: supercash
    password: _#super#_123

  jpa:
    hibernate:
      ddl-auto: update

cash:
  super:
    platform:
      client:
        payment:
          # CASH_SUPER_PLATFORM_CLIENT_PAYMENT_BASEURL MUST BE SET!
          baseUrl: http://localhost:8120/v2/payments

        parkingplus:
          baseUrl: https://maceio.parkingplus.com.br/servicos
          userKey: f313d6a3e46e2a1e1554ed7eb7d286310b924f8f
          retryableDestinationHosts:
            - maceio.parkingplus.com.br
            - demonstracao.parkingplus.com.br
            - payment-service