# SpringBoot
spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

#    keys:
#      http:
#        headers: supercash_tid,supercash_cid

#  sleuth:
#    sampler:
#      probability: 100
#      rate: 30
#    keys:
#      http:
#        headers:
#          supercash_tid
#          new

# Super cash platform
cash:
  super:
    platform:
      service:
        parkingplus:
          # https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-feign.html#_feign_logging
          clientLogLevel: BASIC