# SpringBoot Properties: https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
spring:
  application:
    name: distance-matrix-service

  # Zipkin is the destination environment for the traces and it's disabled in development
  # https://stackoverflow.com/questions/56525260/disable-distributed-tracing-for-development/56529683#56529683
  zipkin:
    enabled: false

  # sleuth is the traces aggregator that's enabled by default, since the gradle dependency is declared with zipkin
  # https://medium.com/@lombos.monika/distributed-tracing-latency-analysis-for-microservices-4ae3b82f3537
  # Read Case 3 for these to propagate the the HTTP Headers
  sleuth:
    baggage:
      remote-fields:
        - "supercash_tid"
        - "supercash_cid"
      correlation-fields:
        - "supercash_tid"
        - "supercash_cid"

logging:
  level:
    org.springframework.core.env: warn
    org.springframework.jndi: warn
    org.springframework.web: DEBUG
    # See which config files are loaded in a given environment
    org.springframework.boot.context.config: DEBUG
    # Log level for the app container
    logging.level.org.apache.tomcat: DEBUG
    logging.level.org.apache.catalina: DEBUG

# here we say that we want to enable accesslog
# https://howtodoinjava.com/spring-boot2/logging/embedded-server-logging-config/
# https://stackoverflow.com/questions/36780680/how-do-you-tell-spring-boot-to-send-the-embedded-tomcats-access-logs-to-stdout/54566643#54566643
server:
  #port: 8080 default
  tomcat:
    accesslog:
      enabled: true
      # /dev/stdout is standard output, so we want tomcat
      # to write to that file descriptor.
      directory: /dev
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:
      # https://tomcat.apache.org/tomcat-8.0-doc/config/valve.html
      # https://howtodoinjava.com/spring-boot2/logging/embedded-server-logging-config/
      # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
      pattern: "%t [ACCESS] %{org.apache.catalina.AccessLog.RemoteAddr}r http_method=%m http_path=%U http_query=%q http_protocol=%H http_status=%s latency_total=%Dms latency_commit=%Fms response_size=%Bbytes %S %u supercash_tid=%{supercash_tid}i supercash_cid=%{supercash_cid}i x_b3_traceid=%{X-B3-TraceId}o"

# SpringFox Swagger
# https://stackoverflow.com/questions/39401010/why-is-v2-api-docs-the-default-url-when-using-springfox-and-swagger2/39453151#39453151
springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/docs/v2

management:
  endpoints:
    web:
      exposure:
        include: "*"

# Super cash platform
cash:
  super:
    platform:
      service:
        distancematrix:
          apiVersion: v1
          language: pt-BR
          # If it's not provided, it will be empty, which will cause it to fail at bootstrap
          googleMapsApiToken: ${google.gcp.distancematrix.credentials.apikey:}

          # Duration the results will stay in memory cache to then be evicted
          resultsCacheDuration: 5

          # java.util.concurrent.TimeUnit https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/TimeUnit.html
          resultsCacheTimeUnit: MINUTES
