# SpringBoot
spring:

  #configs to connect to self register the admin server as a client
  boot:
    admin:
      client:
        instance:
          # The Gateway will forward the calls to /auth/actuator/info...
          management-base-url: https://api.super.cash
          metadata:
            tags:
              env: prd
              cluster: pdc
              segment: prd

  datasource:
    url: jdbc:postgresql://supercash-db-prd.csdmsoazeise.sa-east-1.rds.amazonaws.com:5432/supercash?createDatabaseIfNotExist=true
    username: supercash
    password: .S%etfG=RpJ7A]VH

  jpa:
    hibernate:
      ddl-auto: validate

cash:
  super:
    platform:
      client:
        # Show full HTTP status, body, etc https://www.baeldung.com/java-feign-logging#logging-configuration
        logLevel: HEADERS

      service:
        payment:
          # CASH_SUPER_PLATFORM_CLIENT_PAYMENT_BASEURL MUST BE SET!
          baseUrl: http://localhost:8120/v2/payments
        parkinglot:
          # https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-feign.html#_feign_logging
          baseUrl: https://maceio.parkingplus.com.br/servicos
          # Review this for production
          ourFee: 80
          clientPercentage: 95
          ourPercentage: 5
          saleId: -1
          clientRecipientId: re_cklqt3bhu03t00o9tjjlqxibb
          ourRecipientId: re_cklqszzdc03ra0p9tf9vgkcgl
          apiKeyId: 1
          parkingLotId: 1
          userKey: f313d6a3e46e2a1e1554ed7eb7d286310b924f8f
          saleNameStartWith: MACEIOSHOPPING
          gracePeriod: 1200
          retryableDestinationHosts:
            - maceio.parkingplus.com.br
            - payment-service
            - orchestrator
          retryMaxAttempt: 10
          retryInterval: 5000
