# SpringBoot Properties: https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
spring:
  #configs to connect to self register the admin server as a client
  boot:
    admin:
      client:
        instance:
          # The Gateway will forward the calls to /auth/actuator/info...
          management-base-url: https://api-qal-ppd-prdt.super.cash
          metadata:
            tags:
              env: qal
              segment: ppd
              cluster: prdt

  datasource:
    url: jdbc:postgresql://localhost:6432/supercash?createDatabaseIfNotExist=true
    password: NtiB0Gksl5BspiV1afdPsX3FREEbexxTf3m1XDTv5jTgUCAIXj64dak1w26KEQAI
    hikari:
      maximum-pool-size: 1
    tomcat:
      max-active: 1

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    locations: classpath:db/migration/qal/{vendor}

  mail:
    host: smtp.gmail.com
    username: noreply@super.cash
    password: alsyuchopcytvfmz
    test-connection: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      starttls.required: true
      ssl.enable: true

cash:
  super:
    platform:
      client:
        payment:
          # CASH_SUPER_PLATFORM_CLIENT_PAYMENT_BASEURL MUST BE SET!
          baseUrl: http://localhost:8120/v2/payments

        parkingplus:
          baseUrl: https://maceio.parkingplus.com.br/servicos
          userKey: f313d6a3e46e2a1e1554ed7eb7d286310b924f8f
          retryableDestinationHosts:
            - maceio.parkingplus.com.br
            - demonstracao.parkingplus.com.br
            - payment-service