spring:

  datasource:
    url: jdbc:hsqldb:mem:scratchdb
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    driverClassName: org.hsqldb.jdbc.JDBCDriver