# SpringBoot
spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

#    keys:
#      http:
#        headers: supercash_tid,supercash_cid

#  sleuth:
#    sampler:
#      probability: 100
#      rate: 30
#    keys:
#      http:
#        headers:
#          supercash_tid
#          new

# Super cash platform
cash:
  super:
    platform:
      service:
        distancematrix:
          apiVersion: v1
          language: pt-BR
          # If it's not provided, it will be empty, which will cause it to fail at bootstrap
          googleMapsApiToken: ${google.gcp.distancematrix.credentials.apikey:}

          # Duration the results will stay in memory cache to then be evicted
          resultsCacheDuration: 30

          # java.util.concurrent.TimeUnit https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/TimeUnit.html
          resultsCacheTimeUnit: HOURS