# 029466843584 (paid), 030255713239 (paid), 030255745055, 030255720142,
POST {{host}}:{{port}}/v1/parking_lots/1/users/leandro-123/tickets/030835710600/pay
accept: application/json
X-Supercash-Uid: leandro-123
X-Supercash-Tid: new-transaction20303040
Content-Type: application/json

{
  "payTicketRequest": {
    "amount": 36000,
    "card_number": "4111111111111111",
    "card_cvv": "111",
    "card_expiration_date": "1221",
    "card_holder_name": "Leandro de Sales",
    "customer": {
      "external_id": "#0001",
      "name": "Leandro de Sales",
      "type": "INDIVIDUAL",
      "email": "leandro@super.cash",
      "documents": [
        {
          "type": "CPF",
          "number": "03817304412"
        }
      ],
      "phone_numbers": ["+5582999378000"]
    },
    "billing": {
      "name": "Leandro Melo Sales",
      "address": {
        "state": "SP",
        "city": "São Paulo",
        "neighborhood": "Morumbi",
        "street": "Rua do Flamengo",
        "street_number": "10A",
        "zipcode": "11010001",
        "complementary": "Apto 104"
      }
    },
    "items": [
      {
        "id": "030835710600",
        "unit_price": 36000
      }
    ],
    "metadata": {
      "device_id": "1",
      "private_ip": "10.0.0.1",
      "public_ip": "10.0.0.1",
      "lapsed_time": 3600
    }
  }
}