POST {{host}}:{{port}}/v1/parking_lot/1/users/leandro-123/tickets/030265292584/pay
accept: application/json
X-Supercash-Uid: leandro-123
X-Supercash-Tid: new-transaction20303040
X-Supercash-MarketplaceId: 123
X-Supercash-StoreId: 456
Content-Type: application/json

{
  "request": {
    "numeroTicket": "030265292584",
    "enderecoIp": "10.0.0.1",
    "cartaoDeCredito": 4111111111111111,
    "codigoDeSeguranca": "111",
    "validade": "1221",
    "portador": "Leandro de Sales",
    "valor": 700
  }
}

