POST {{host}}:{{port}}/v2/parking_lot/tickets/326503194981/pay
accept: application/json
X-Supercash-Uid: 14727
X-Supercash-Tid: new-transaction20303040
X-Supercash-Marketplace-Id: 6115
X-Supercash-Store-Id: 1
X-Supercash-App-Version: 1.0
Content-Type: application/json
Accept-Encoding: application/json

{
  "request": {
    "numeroTicket": "326503194981",
    "enderecoIp": "10.0.0.1",
    "cartaoDeCredito": 4111111111111111,
    "codigoDeSeguranca": "111",
    "validade": "1221",
    "portador": "Leandro de Sales",
    "valor": 700
  }
}

