POST {{host}}:{{port}}/v2/parking_lot/tickets/273647526466/pay
accept: application/json
X-Supercash-Uid: 99999
X-Supercash-Tid: new-transaction202
X-Supercash-Marketplace-Id: 6115
X-Supercash-Store-Id: 51
X-Supercash-App-Version: 1.0
Content-Type: application/json
Accept-Encoding: application/json

{
  "anonymousTicketPaymentRequest": {
    "reference_id": "273647526466",
    "amount": {
      "value": 2100,
      "currency": "BRL"
    },
    "payment_method": {
      "card": {
        "number": "4111111111111111",
        "exp_month": 3,
        "exp_year": 2026,
        "security_code": 123,
        "holder": {
          "name": "Marcello de Sales Jr"
        }
      }
    },
    "metadata": {
      "public_ip":"23.125.120.55",
      "user_agent":"Chrome 1.1",
      "lapsed_time":6735,
      "credit_card_issuer":"Visa"
    }
  }
}