GET http://localhost:8080/v1/parking_lots/1/users/marcello-123/payment/servicefee
Accept: application/json
X-Supercash-Uid: marcello-123
X-Supercash-Tid: new-transaction20303040
Content-Type: application/json
Accept-Encoding: application/json

