POST http://localhost:8080/v1/parking_lots/1/users/marcello-123/tickets/029466836971/pay
accept: application/json
X-Supercash-Uid: marcello-123
X-Supercash-Tid: new-transaction20303040
Content-Type: application/json

{
  "authorizedRequest": {
    "idTransacao": "supercash-payment-3",
    "numeroTicket": "029466836971",
    "valor": 100
  }
}

###

