# https://gitlab.com/supercash/apps-web/maceio-shopping-tickets-web/-/wikis/Backend-Testing-API
# When getting status for ticket 111111000000, we should see a ticket that can be paid, but the user will never leave the parking lot
GET {{host}}:{{port}}/v2/parking_lot/tickets/111111000000
Accept: application/json
X-Supercash-Uid: 99999
X-Supercash-Tid: new-transaction20303040
X-Supercash-MarketplaceId: 6115
X-Supercash-StoreId: 51
X-Supercash-App-Version: 1.0
Content-Type: application/json
Accept-Encoding: application/json