version: '3.8'

networks:

  supercash-data-network:
    name: supercash-data-network

services:
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8778:8080
    networks:
      - supercash-data-network
