GET {{host}}:{{port}}/v1/parking_lot/1/users/marcello-123/tickets
Accept: application/json
X-Supercash-Uid: marcello-123
X-Supercash-Tid: new-transaction20303040
Content-Type: application/json
Accept-Encoding: application/json