# Regular ticket status
GET {{host}}:{{port}}/v2/parkinglots/1/tickets/247475886066?scanned=true
Accept: application/json
X-Supercash-Uid: 14727
X-Supercash-Tid: new-transaction20303042
X-Supercash-Marketplace-Id: 6115
X-Supercash-Store-Id: 14791
X-Supercash-App-Version: 1.0
Content-Type: application/json
Accept-Encoding: application/json