# Regular ticket status
GET {{host}}:{{port}}/v2/parkinglots/14791/tickets/327274927710
Accept: application/json
X-Supercash-Uid: 1200
X-Supercash-Tid: new-transaction20303042
X-Supercash-Marketplace-Id: 6115
X-Supercash-Store-Id: 1
X-Supercash-App-Version: 1.0
Content-Type: application/json
Accept-Encoding: application/json