# Regular ticket status
GET {{host}}:{{port}}/v2/parking_lot/tickets/327274927710
Accept: application/json
X-Supercash-Uid: 1200
X-Supercash-Tid: new-transaction20303042
X-Supercash-MarketplaceId: 6115
X-Supercash-StoreId: 1
X-Supercash-App-Version: 1.0
Content-Type: application/json
Accept-Encoding: application/json