# Regular ticket status
GET {{host}}:{{port}}/v2/parkinglots/14791/tickets/248361679911
Accept: application/json
X-Supercash-Uid: 14727
X-Supercash-Tid: new-transaction20303043
X-Supercash-Marketplace-Id: 14824
X-Supercash-Store-Id: 14791
X-Supercash-App-Version: 1.0
Content-Type: application/json
Accept-Encoding: application/json