GET {{host}}:{{port}}/v2/parking_lot/1/users/leandro-123/sales
Accept: application/json
X-Supercash-Uid: leandro-123
X-Supercash-Tid: new-transaction20303040
X-Supercash-MarketplaceId: 123
X-Supercash-StoreId: 456
Content-Type: application/json
Accept-Encoding: application/json
