GET {{host}}:{{port}}/v2/parking_lot/sales
Accept: application/json
X-Supercash-Uid: leandro-123
X-Supercash-Tid: new-transaction20303040
X-Supercash-Marketplace-Id: 123
X-Supercash-Store-Id: 456
Content-Type: application/json
Accept-Encoding: application/json
