# You can pass ?validate=false as request parameter to force receiving the sales response without validation
GET {{host}}:{{port}}/v1/parking_lot/1/users/leandro-123/sales/15
Accept: application/json
X-Supercash-Uid: leandro-123
X-Supercash-Tid: new-transaction20303040
Content-Type: application/json
Accept-Encoding: application/json